from math import ceil

QUESTIONS = [
    {
        "id": "body_type",
        "label": "What body type do you like?",
        "description": "Choose the shape that fits your taste or leave it wide open.",
        "options": [
            ("no_preference", "No preference"),
            ("coupe", "Coupe"),
            ("sedan", "Sedan"),
            ("hatchback", "Hatchback"),
            ("wagon", "Wagon"),
            ("roadster", "Roadster / Convertible"),
            ("suv", "SUV / Crossover"),
        ],
    },
    {
        "id": "drivetrain",
        "label": "Which drivetrain do you prefer?",
        "description": "Rear-wheel drive, front-wheel drive, all-wheel drive, or no preference.",
        "options": [
            ("no_preference", "No preference"),
            ("rwd", "RWD"),
            ("fwd", "FWD"),
            ("awd", "AWD"),
        ],
    },
    {
        "id": "differential",
        "label": "What kind of differential setup are you after?",
        "description": "Useful if you care about traction behavior or track-friendly hardware.",
        "options": [
            ("no_preference", "No preference"),
            ("open", "Open differential"),
            ("lsd", "LSD / limited-slip"),
        ],
    },
    {
        "id": "year_range",
        "label": "Which year range feels right?",
        "description": "Pick a decade and the matcher will include cars whose production overlaps that era.",
        "options": [
            ("no_preference", "No preference"),
            ("1970s", "1970s"),
            ("1980s", "1980s"),
            ("1990s", "1990s"),
            ("2000s", "2000s"),
            ("2010s", "2010s"),
            ("2020s", "2020s"),
        ],
    },
    {
        "id": "driving_priority",
        "label": "What matters more to you?",
        "description": "Lean toward nimble handling, straight-line punch, or a balanced setup.",
        "options": [
            ("no_preference", "No preference"),
            ("handling", "Good handling"),
            ("straight_line", "Good straight-line speed"),
            ("balanced", "Balanced all-rounder"),
        ],
    },
    {
        "id": "transmission",
        "label": "Transmission preference?",
        "description": "Useful if shifting experience matters to you.",
        "options": [
            ("no_preference", "No preference"),
            ("manual", "Manual"),
            ("automatic", "Automatic / DCT"),
        ],
    },
    {
        "id": "powertrain",
        "label": "Engine character preference?",
        "description": "Natural response or boosted torque, if you care.",
        "options": [
            ("no_preference", "No preference"),
            ("na", "Naturally aspirated"),
            ("forced_induction", "Turbo / Supercharged"),
        ],
    },
]

OPTION_LABELS = {
    question["id"]: {value: label for value, label in question["options"]}
    for question in QUESTIONS
}

CARS = [
    {
        "name": "Mazda MX-5 Miata ND2",
        "body_type": "roadster",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 2019,
        "year_end": 2024,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "Mazda_MX-5",
        "summary": "Light, simple, and one of the easiest ways to prioritize feel over raw speed.",
    },
    {
        "name": "Toyota GR86 / Subaru BRZ",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 2022,
        "year_end": 2025,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "Toyota_86",
        "summary": "Playful chassis, usable size, and a strong choice for people who value balance first.",
    },
    {
        "name": "Honda Civic Type R FK8",
        "body_type": "hatchback",
        "drivetrain": "fwd",
        "differential": "lsd",
        "year_start": 2017,
        "year_end": 2021,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "forced_induction",
        "image_page": "Honda_Civic_Type_R",
        "summary": "A front-drive benchmark with real practicality and a serious chassis.",
    },
    {
        "name": "Volkswagen Golf R Mk7.5",
        "body_type": "hatchback",
        "drivetrain": "awd",
        "differential": "open",
        "year_start": 2018,
        "year_end": 2019,
        "driving_priority": "balanced",
        "transmission": "automatic",
        "powertrain": "forced_induction",
        "image_page": "Volkswagen_Golf_Mk7",
        "summary": "Fast in all weather, easy to live with, and quietly effective.",
    },
    {
        "name": "BMW M2 Competition",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 2019,
        "year_end": 2021,
        "driving_priority": "balanced",
        "transmission": "automatic",
        "powertrain": "forced_induction",
        "image_page": "BMW_M2",
        "summary": "Compact, fast, and aggressive without losing too much street friendliness.",
    },
    {
        "name": "Ford Mustang GT S550",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 2015,
        "year_end": 2023,
        "driving_priority": "straight_line",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "Ford_Mustang_(sixth_generation)",
        "summary": "Big V8 energy with broad aftermarket support and genuine value per horsepower.",
    },
    {
        "name": "Chevrolet Camaro SS 1LE",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 2017,
        "year_end": 2024,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "Chevrolet_Camaro_(sixth_generation)",
        "summary": "More track-focused than people expect, with serious chassis performance.",
    },
    {
        "name": "Porsche Cayman 987.2",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 2009,
        "year_end": 2012,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "Porsche_Boxster/Cayman",
        "summary": "Mid-engine composure and a focused driving experience without going full exotic.",
    },
    {
        "name": "Subaru WRX STI VA",
        "body_type": "sedan",
        "drivetrain": "awd",
        "differential": "lsd",
        "year_start": 2015,
        "year_end": 2021,
        "driving_priority": "balanced",
        "transmission": "manual",
        "powertrain": "forced_induction",
        "image_page": "Subaru_WRX",
        "summary": "Old-school AWD character, manual only, and a mechanical feel some buyers still love.",
    },
    {
        "name": "Mitsubishi Lancer Evolution X",
        "body_type": "sedan",
        "drivetrain": "awd",
        "differential": "lsd",
        "year_start": 2008,
        "year_end": 2015,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "forced_induction",
        "image_page": "Mitsubishi_Lancer_Evolution_X",
        "summary": "Pointy, quick, and still one of the iconic AWD driver cars.",
    },
    {
        "name": "BMW 340i xDrive G20",
        "body_type": "sedan",
        "drivetrain": "awd",
        "differential": "open",
        "year_start": 2020,
        "year_end": 2025,
        "driving_priority": "straight_line",
        "transmission": "automatic",
        "powertrain": "forced_induction",
        "image_page": "BMW_3_Series_(G20)",
        "summary": "A fast daily sedan with tuning headroom and excellent real-world pace.",
    },
    {
        "name": "Cadillac CT4-V Blackwing",
        "body_type": "sedan",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 2022,
        "year_end": 2025,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "forced_induction",
        "image_page": "Cadillac_CT4",
        "summary": "One of the last great manual sport sedans with a sharp chassis and real personality.",
    },
    {
        "name": "Audi RS3 8Y",
        "body_type": "sedan",
        "drivetrain": "awd",
        "differential": "lsd",
        "year_start": 2022,
        "year_end": 2025,
        "driving_priority": "straight_line",
        "transmission": "automatic",
        "powertrain": "forced_induction",
        "image_page": "Audi_RS_3",
        "summary": "Huge launch performance and a charismatic five-cylinder soundtrack in a small sedan package.",
    },
    {
        "name": "Mercedes-AMG C63 W204",
        "body_type": "sedan",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 2008,
        "year_end": 2014,
        "driving_priority": "straight_line",
        "transmission": "automatic",
        "powertrain": "na",
        "image_page": "Mercedes-Benz_C-Class_(W204)",
        "summary": "Naturally aspirated V8 drama with rear-drive attitude and real muscle-car flavor.",
    },
    {
        "name": "Honda S2000",
        "body_type": "roadster",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 2000,
        "year_end": 2009,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "Honda_S2000",
        "summary": "A high-revving icon for people who want a focused, tactile, naturally aspirated sports car.",
    },
    {
        "name": "Volkswagen GTI Mk7",
        "body_type": "hatchback",
        "drivetrain": "fwd",
        "differential": "open",
        "year_start": 2015,
        "year_end": 2021,
        "driving_priority": "balanced",
        "transmission": "manual",
        "powertrain": "forced_induction",
        "image_page": "Volkswagen_Golf_Mk7",
        "summary": "A practical hot hatch with an approachable balance of speed, comfort, and tuning support.",
    },
    {
        "name": "Toyota GR Corolla",
        "body_type": "hatchback",
        "drivetrain": "awd",
        "differential": "lsd",
        "year_start": 2023,
        "year_end": 2025,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "forced_induction",
        "image_page": "Toyota_GR_Corolla",
        "summary": "Short-wheelbase AWD chaos in the best way, with real enthusiast hardware.",
    },
    {
        "name": "Dodge Charger Scat Pack",
        "body_type": "sedan",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 2015,
        "year_end": 2023,
        "driving_priority": "straight_line",
        "transmission": "automatic",
        "powertrain": "na",
        "image_page": "Dodge_Charger_(LX/LD)",
        "summary": "A roomy sedan that leans into power, noise, and easy straight-line fun.",
    },
    {
        "name": "Porsche 911 Carrera 997",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "open",
        "year_start": 2005,
        "year_end": 2012,
        "driving_priority": "balanced",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "Porsche_997",
        "summary": "Compact, special, and broad in ability without losing classic 911 character.",
    },
    {
        "name": "BMW M3 Touring G81",
        "body_type": "wagon",
        "drivetrain": "awd",
        "differential": "lsd",
        "year_start": 2023,
        "year_end": 2025,
        "driving_priority": "balanced",
        "transmission": "automatic",
        "powertrain": "forced_induction",
        "image_page": "BMW_M3",
        "summary": "A fast family car that combines space, traction, and real M-car performance.",
    },
    {
        "name": "Nissan Silvia S15 Spec-R",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 1999,
        "year_end": 2002,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "forced_induction",
        "image_page": "Nissan_Silvia",
        "summary": "A lightweight turbo RWD coupe with huge tuner appeal and exactly the kind of analog feel Silvia fans want.",
    },
    {
        "name": "Nissan 180SX Type X",
        "body_type": "hatchback",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 1996,
        "year_end": 1998,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "forced_induction",
        "image_page": "Nissan_180SX",
        "summary": "Pop-up lights, turbo SR power, and one of the most loved rear-drive drift and street platforms.",
    },
    {
        "name": "Nissan 350Z",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 2003,
        "year_end": 2009,
        "driving_priority": "balanced",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "Nissan_350Z",
        "summary": "Simple rear-drive coupe value with a strong VQ soundtrack and a big aftermarket.",
    },
    {
        "name": "Mazda RX-7 FD",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 1992,
        "year_end": 2002,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "forced_induction",
        "image_page": "Mazda_RX-7",
        "summary": "Low, light, and sharp with iconic rotary turbo character and real collector appeal.",
    },
    {
        "name": "Toyota MR2 SW20 Turbo",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "open",
        "year_start": 1991,
        "year_end": 1999,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "forced_induction",
        "image_page": "Toyota_MR2",
        "summary": "Mid-engine proportions and old-school turbo charm for buyers who want something less common.",
    },
    {
        "name": "Toyota Altezza RS200",
        "body_type": "sedan",
        "drivetrain": "rwd",
        "differential": "open",
        "year_start": 1998,
        "year_end": 2005,
        "driving_priority": "balanced",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "Toyota_Altezza",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Toyota_Altezza_%2844307261631%29.jpg/1280px-Toyota_Altezza_%2844307261631%29.jpg",
        "summary": "Compact rear-drive sedan energy with revvy naturally aspirated character and genuine JDM appeal.",
    },
    {
        "name": "BMW M3 E46",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 2001,
        "year_end": 2006,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "BMW_M3_(E46)",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/E46_M3.jpg/1280px-E46_M3.jpg",
        "summary": "A classic benchmark for analog steering feel, balance, and usable performance.",
    },
    {
        "name": "Acura Integra Type R DC2",
        "body_type": "coupe",
        "drivetrain": "fwd",
        "differential": "lsd",
        "year_start": 1997,
        "year_end": 2001,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "Honda_Integra",
        "summary": "One of the purest front-drive handling cars ever built, with a screaming naturally aspirated engine.",
    },
    {
        "name": "Toyota AE86 Corolla Levin / Trueno",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "open",
        "year_start": 1983,
        "year_end": 1987,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "Toyota_AE86",
        "summary": "Slow by modern standards but famous for lightness, balance, and driver involvement.",
    },
    {
        "name": "Nissan Skyline GT-R R34",
        "body_type": "coupe",
        "drivetrain": "awd",
        "differential": "lsd",
        "year_start": 1999,
        "year_end": 2002,
        "driving_priority": "balanced",
        "transmission": "manual",
        "powertrain": "forced_induction",
        "image_page": "Nissan_Skyline_GT-R",
        "summary": "An all-time hero car with enormous tuning potential, grip, and road presence.",
    },
    {
        "name": "BMW 1M Coupe",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 2011,
        "year_end": 2012,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "forced_induction",
        "image_page": "BMW_1_Series_M_Coup%C3%A9",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/BMW_1_Series_M_Coupe_2011.jpg/1280px-BMW_1_Series_M_Coupe_2011.jpg",
        "summary": "Short-wheelbase turbo BMW attitude with a rawer feel than many newer M cars.",
    },
    {
        "name": "Lotus Elise S2",
        "body_type": "roadster",
        "drivetrain": "rwd",
        "differential": "open",
        "year_start": 2001,
        "year_end": 2011,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "Lotus_Elise",
        "summary": "Minimal weight, telepathic steering, and one of the purest handling experiences ever sold for the road.",
    },
    {
        "name": "Lotus Exige S2",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "open",
        "year_start": 2004,
        "year_end": 2011,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "Lotus_Exige",
        "summary": "An Elise turned sharper and angrier, ideal for buyers who want a focused weekend weapon.",
    },
    {
        "name": "Mazda RX-8 R3",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 2009,
        "year_end": 2011,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "Mazda_RX-8",
        "summary": "A practical rotary sports coupe with a brilliant chassis and unusual character.",
    },
    {
        "name": "Toyota Supra A80 Turbo",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 1993,
        "year_end": 2002,
        "driving_priority": "straight_line",
        "transmission": "manual",
        "powertrain": "forced_induction",
        "image_page": "Toyota_Supra",
        "summary": "Legendary 2JZ turbo tuning platform with serious highway pace and long-term hero status.",
    },
    {
        "name": "Toyota Chaser Tourer V",
        "body_type": "sedan",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 1996,
        "year_end": 2001,
        "driving_priority": "balanced",
        "transmission": "manual",
        "powertrain": "forced_induction",
        "image_page": "Toyota_Chaser",
        "summary": "Rear-drive sedan practicality mixed with 1JZ turbo tuning appeal and drift credibility.",
    },
    {
        "name": "Nissan Laurel C35 Club S",
        "body_type": "sedan",
        "drivetrain": "rwd",
        "differential": "open",
        "year_start": 1997,
        "year_end": 2002,
        "driving_priority": "balanced",
        "transmission": "automatic",
        "powertrain": "na",
        "image_page": "Nissan_Laurel",
        "summary": "A less obvious JDM rear-drive sedan choice with skyline-adjacent underpinnings and sleeper appeal.",
    },
    {
        "name": "Nissan Stagea 260RS",
        "body_type": "wagon",
        "drivetrain": "awd",
        "differential": "lsd",
        "year_start": 1997,
        "year_end": 2001,
        "driving_priority": "balanced",
        "transmission": "manual",
        "powertrain": "forced_induction",
        "image_page": "Nissan_Stagea",
        "summary": "Skyline GT-R energy in wagon form for people who want practicality without losing cult status.",
    },
    {
        "name": "Mitsubishi GTO / 3000GT VR-4",
        "body_type": "coupe",
        "drivetrain": "awd",
        "differential": "lsd",
        "year_start": 1990,
        "year_end": 2000,
        "driving_priority": "straight_line",
        "transmission": "manual",
        "powertrain": "forced_induction",
        "image_page": "Mitsubishi_GTO",
        "summary": "Heavy but loaded with technology, traction, and twin-turbo highway speed.",
    },
    {
        "name": "Subaru Impreza 22B STI",
        "body_type": "coupe",
        "drivetrain": "awd",
        "differential": "lsd",
        "year_start": 1998,
        "year_end": 1998,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "forced_induction",
        "image_page": "Subaru_Impreza_WRX_STI",
        "summary": "One of the most iconic rally-bred coupes ever built, short-production and hugely special.",
    },
    {
        "name": "Renault Clio RS 182",
        "body_type": "hatchback",
        "drivetrain": "fwd",
        "differential": "open",
        "year_start": 2004,
        "year_end": 2005,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "Renault_Clio_V6_Renault_Sport",
        "summary": "Small, eager, and playful in a way that made compact hot hatches famous.",
    },
    {
        "name": "Peugeot 106 Rallye",
        "body_type": "hatchback",
        "drivetrain": "fwd",
        "differential": "open",
        "year_start": 1993,
        "year_end": 1998,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "Peugeot_106",
        "summary": "Tiny, light, and mischievous, with old-school hot hatch simplicity and feel.",
    },
    {
        "name": "Alfa Romeo 147 GTA",
        "body_type": "hatchback",
        "drivetrain": "fwd",
        "differential": "open",
        "year_start": 2002,
        "year_end": 2005,
        "driving_priority": "straight_line",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "Alfa_Romeo_147",
        "summary": "A dramatic V6 hot hatch for buyers who value character as much as objective pace.",
    },
    {
        "name": "Ford Fiesta ST Mk7",
        "body_type": "hatchback",
        "drivetrain": "fwd",
        "differential": "open",
        "year_start": 2013,
        "year_end": 2019,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "forced_induction",
        "image_page": "Ford_Fiesta_ST",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Ford_Fiesta_ST_MK7_Leonberg_2019_IMG_0054.jpg/1280px-Ford_Fiesta_ST_MK7_Leonberg_2019_IMG_0054.jpg",
        "summary": "One of the best affordable front-drive cars for people who want fun more than headline stats.",
    },
    {
        "name": "BMW Z4 M Coupe",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 2006,
        "year_end": 2008,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "BMW_Z4_(E85)",
        "summary": "A rare shooting-brake-style BMW with M3 engine drama and serious driver focus.",
    },
    {
        "name": "BMW Z3 M Coupe",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 1998,
        "year_end": 2002,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "BMW_M_Coup%C3%A9_and_M_Roadster",
        "summary": "Oddball proportions, big personality, and a cult following for good reason.",
    },
    {
        "name": "Mercedes-Benz 190E 2.3-16",
        "body_type": "sedan",
        "drivetrain": "rwd",
        "differential": "open",
        "year_start": 1984,
        "year_end": 1991,
        "driving_priority": "balanced",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "Mercedes-Benz_W201",
        "summary": "A crisp old-school sport sedan that overlaps the late 1980s and early 1990s exactly the way decade matching should catch.",
    },
    {
        "name": "BMW E30 325i Coupe",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "open",
        "year_start": 1985,
        "year_end": 1991,
        "driving_priority": "balanced",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "BMW_3_Series_(E30)",
        "summary": "Classic rear-drive BMW balance with a broad enthusiast community and simple mechanical feel.",
    },
    {
        "name": "Porsche 944 Turbo",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "open",
        "year_start": 1985,
        "year_end": 1991,
        "driving_priority": "balanced",
        "transmission": "manual",
        "powertrain": "forced_induction",
        "image_page": "Porsche_944",
        "summary": "Transaxle balance, turbo shove, and a very different Porsche flavor than a rear-engine 911.",
    },
    {
        "name": "Chevrolet Corvette C5 Z06",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 2001,
        "year_end": 2004,
        "driving_priority": "straight_line",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "Chevrolet_Corvette_(C5)",
        "summary": "Excellent performance value with huge V8 pace and respectable track ability.",
    },
    {
        "name": "Chevrolet Corvette C6 Grand Sport",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 2010,
        "year_end": 2013,
        "driving_priority": "balanced",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "Chevrolet_Corvette_(C6)",
        "summary": "Strong naturally aspirated V8 performance with a broad capability range and great value.",
    },
    {
        "name": "Honda NSX NA1",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "open",
        "year_start": 1990,
        "year_end": 2001,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "Honda_NSX",
        "summary": "A landmark Japanese mid-engine car with usability, precision, and long-term significance.",
    },
    {
        "name": "Ferrari 458 Italia",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 2009,
        "year_end": 2015,
        "driving_priority": "handling",
        "transmission": "automatic",
        "powertrain": "na",
        "image_page": "Ferrari_458",
        "summary": "A naturally aspirated high point of modern exotic cars with precision and theatre in equal measure.",
    },
    {
        "name": "Audi TT RS 8J",
        "body_type": "coupe",
        "drivetrain": "awd",
        "differential": "open",
        "year_start": 2009,
        "year_end": 2014,
        "driving_priority": "straight_line",
        "transmission": "manual",
        "powertrain": "forced_induction",
        "image_page": "Audi_TT",
        "summary": "Compact shape, five-cylinder soundtrack, and strong all-weather pace.",
    },
    {
        "name": "Porsche 718 Cayman GTS 4.0",
        "body_type": "coupe",
        "drivetrain": "rwd",
        "differential": "lsd",
        "year_start": 2020,
        "year_end": 2025,
        "driving_priority": "handling",
        "transmission": "manual",
        "powertrain": "na",
        "image_page": "Porsche_718_Cayman",
        "summary": "One of the best current-era sports car choices for buyers who still care about feel and response.",
    },
    {
        "name": "Honda Accord 2.0T Touring",
        "body_type": "sedan",
        "drivetrain": "fwd",
        "differential": "open",
        "year_start": 2018,
        "year_end": 2022,
        "driving_priority": "balanced",
        "transmission": "automatic",
        "powertrain": "forced_induction",
        "image_page": "Honda_Accord",
        "summary": "A genuinely strong mainstream sedan choice with space, comfort, and enough pace to avoid feeling dull.",
    },
    {
        "name": "Honda Accord Hybrid",
        "body_type": "sedan",
        "drivetrain": "fwd",
        "differential": "open",
        "year_start": 2023,
        "year_end": 2025,
        "driving_priority": "balanced",
        "transmission": "automatic",
        "powertrain": "na",
        "image_page": "Honda_Accord",
        "summary": "Comfortable, quiet, and efficient, for buyers who want a sensible daily without crossover bulk.",
    },
    {
        "name": "Toyota Camry V6 XSE",
        "body_type": "sedan",
        "drivetrain": "fwd",
        "differential": "open",
        "year_start": 2018,
        "year_end": 2024,
        "driving_priority": "straight_line",
        "transmission": "automatic",
        "powertrain": "na",
        "image_page": "Toyota_Camry_(XV70)",
        "summary": "A familiar midsize sedan with a smooth V6 and more speed than its reputation suggests.",
    },
    {
        "name": "Toyota Camry Hybrid",
        "body_type": "sedan",
        "drivetrain": "fwd",
        "differential": "open",
        "year_start": 2018,
        "year_end": 2025,
        "driving_priority": "balanced",
        "transmission": "automatic",
        "powertrain": "na",
        "image_page": "Toyota_Camry_(XV70)",
        "summary": "A sensible, efficient, long-term reliable sedan for buyers who just want a good car that works.",
    },
    {
        "name": "Toyota Camry LE / SE",
        "body_type": "sedan",
        "drivetrain": "fwd",
        "differential": "open",
        "year_start": 2020,
        "year_end": 2025,
        "driving_priority": "balanced",
        "transmission": "automatic",
        "powertrain": "na",
        "image_page": "Toyota_Camry_(XV70)",
        "summary": "The classic mainstream sedan answer: comfortable, easy to own, and exactly the kind of normal car many people actually want.",
    },
    {
        "name": "Toyota Avalon",
        "body_type": "sedan",
        "drivetrain": "fwd",
        "differential": "open",
        "year_start": 2019,
        "year_end": 2022,
        "driving_priority": "balanced",
        "transmission": "automatic",
        "powertrain": "na",
        "image_page": "Toyota_Avalon",
        "summary": "A roomy near-luxury Toyota sedan that leans into comfort and easy long-distance use.",
    },
    {
        "name": "Mazda6 2.5 Turbo",
        "body_type": "sedan",
        "drivetrain": "fwd",
        "differential": "open",
        "year_start": 2018,
        "year_end": 2021,
        "driving_priority": "balanced",
        "transmission": "automatic",
        "powertrain": "forced_induction",
        "image_page": "Mazda6",
        "summary": "One of the more stylish and better-driving mainstream midsize sedans of its era.",
    },
    {
        "name": "Mazda3 Sedan",
        "body_type": "sedan",
        "drivetrain": "fwd",
        "differential": "open",
        "year_start": 2019,
        "year_end": 2025,
        "driving_priority": "balanced",
        "transmission": "automatic",
        "powertrain": "na",
        "image_page": "Mazda3",
        "summary": "A compact sedan with cleaner styling and a slightly more polished feel than many class rivals.",
    },
    {
        "name": "Honda Civic Sedan 2.0",
        "body_type": "sedan",
        "drivetrain": "fwd",
        "differential": "open",
        "year_start": 2022,
        "year_end": 2025,
        "driving_priority": "balanced",
        "transmission": "automatic",
        "powertrain": "na",
        "image_page": "Honda_Civic_(eleventh_generation)",
        "summary": "A clean, practical compact sedan with solid dynamics and easy everyday manners.",
    },
    {
        "name": "Toyota Corolla Sedan",
        "body_type": "sedan",
        "drivetrain": "fwd",
        "differential": "open",
        "year_start": 2020,
        "year_end": 2025,
        "driving_priority": "balanced",
        "transmission": "automatic",
        "powertrain": "na",
        "image_page": "Toyota_Corolla_(E210)",
        "summary": "Simple, durable, and predictable in the exact way many buyers actually want.",
    },
    {
        "name": "Nissan Altima SR",
        "body_type": "sedan",
        "drivetrain": "fwd",
        "differential": "open",
        "year_start": 2019,
        "year_end": 2025,
        "driving_priority": "balanced",
        "transmission": "automatic",
        "powertrain": "na",
        "image_page": "Nissan_Altima",
        "summary": "A mainstream midsize sedan option for buyers who want something ordinary, modern, and widely available.",
    },
    {
        "name": "Hyundai Sonata N Line",
        "body_type": "sedan",
        "drivetrain": "fwd",
        "differential": "open",
        "year_start": 2021,
        "year_end": 2025,
        "driving_priority": "straight_line",
        "transmission": "automatic",
        "powertrain": "forced_induction",
        "image_page": "Hyundai_Sonata",
        "summary": "A front-drive family sedan with unexpectedly strong straight-line performance.",
    },
    {
        "name": "Hyundai Elantra",
        "body_type": "sedan",
        "drivetrain": "fwd",
        "differential": "open",
        "year_start": 2021,
        "year_end": 2025,
        "driving_priority": "balanced",
        "transmission": "automatic",
        "powertrain": "na",
        "image_page": "Hyundai_Elantra",
        "summary": "A practical compact sedan pick with strong equipment value and a low-drama ownership brief.",
    },
    {
        "name": "Kia K5 GT-Line",
        "body_type": "sedan",
        "drivetrain": "fwd",
        "differential": "open",
        "year_start": 2021,
        "year_end": 2025,
        "driving_priority": "balanced",
        "transmission": "automatic",
        "powertrain": "forced_induction",
        "image_page": "Kia_K5",
        "summary": "A sharper-looking midsize sedan for buyers who want normal-car usability without crossover styling.",
    },
    {
        "name": "Volkswagen Passat",
        "body_type": "sedan",
        "drivetrain": "fwd",
        "differential": "open",
        "year_start": 2016,
        "year_end": 2022,
        "driving_priority": "balanced",
        "transmission": "automatic",
        "powertrain": "forced_induction",
        "image_page": "Volkswagen_Passat_(North_America_and_China)",
        "summary": "A plain but roomy sedan that suits buyers who prioritize comfort and straightforward daily use.",
    },
    {
        "name": "Subaru Legacy",
        "body_type": "sedan",
        "drivetrain": "awd",
        "differential": "open",
        "year_start": 2020,
        "year_end": 2025,
        "driving_priority": "balanced",
        "transmission": "automatic",
        "powertrain": "na",
        "image_page": "Subaru_Legacy",
        "summary": "An all-wheel-drive family sedan for buyers who want a normal car with winter-weather confidence.",
    },
    {
        "name": "Toyota Crown",
        "body_type": "sedan",
        "drivetrain": "awd",
        "differential": "open",
        "year_start": 2023,
        "year_end": 2025,
        "driving_priority": "balanced",
        "transmission": "automatic",
        "powertrain": "na",
        "image_page": "Toyota_Crown",
        "summary": "A modern sedan-like Toyota choice that sits between mainstream and near-premium sensibility.",
    },
    {
        "name": "Lexus ES 350",
        "body_type": "sedan",
        "drivetrain": "fwd",
        "differential": "open",
        "year_start": 2019,
        "year_end": 2025,
        "driving_priority": "balanced",
        "transmission": "automatic",
        "powertrain": "na",
        "image_page": "Lexus_ES",
        "summary": "Quiet, soft, and durable in exactly the way many luxury-sedan buyers actually want.",
    },
    {
        "name": "Acura TLX FWD",
        "body_type": "sedan",
        "drivetrain": "fwd",
        "differential": "open",
        "year_start": 2021,
        "year_end": 2025,
        "driving_priority": "balanced",
        "transmission": "automatic",
        "powertrain": "forced_induction",
        "image_page": "Acura_TLX",
        "summary": "A slightly sportier-feeling premium sedan without jumping all the way into hard-core enthusiast territory.",
    },
]


def get_default_answers():
    return {question["id"]: "no_preference" for question in QUESTIONS}


def get_selected_criteria(answers):
    criteria = []
    for question in QUESTIONS:
        value = answers.get(question["id"], "no_preference")
        if value == "no_preference":
            continue
        criteria.append(
            {
                "id": question["id"],
                "label": question["label"],
                "values": [value],
                "value_labels": [OPTION_LABELS[question["id"]][value]],
                "value_label": OPTION_LABELS[question["id"]][value],
            }
        )
    return criteria


def honorable_miss_limit(selected_count):
    if selected_count <= 0:
        return 0
    return max(1, ceil(selected_count * 0.25))
